#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
FILESDIR_PATH="${DOCROOT_PATH}/files/"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${FILESDIR_PATH}"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH
	
	echo "Downloading Backdrop Drush Commands..."
	sudo rm -rf ~/.drush/backdrop
	sudo git clone https://github.com/backdrop-contrib/drush.git ~/.drush/backdrop > /dev/null

	 drush si standard \
	 -y \
	 --site-name='AltaGrade Developer Stack' \
	 --db-url='mysqli://user:user@db/default' \
	 --account-mail="admin@example.com" \
	 --account-name="admin" \
	 --account-pass="admin" || true

	# Alternative way to switch to until 
	# https://github.com/backdrop-contrib/drush/issues/195 is resolved.
	# cd $DOCROOT_PATH
	# ./core/scripts/install.sh \
  	# --db-url='mysql://user:user@db/default' \
	# --account-mail="admin@example.com" \
	# --account-name="admin" \
	# --account-pass="admin" \
	# --site-mail="admin@example.com" \
  	# --site-name='AltaGrade Developer Stack' > /dev/null 2>&1 &

	# Currently a way to set password at runtime with drush site-install
	drush upwd admin --password=admin > /dev/null
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Preparing bash --------------------------------

sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/g' ~/.bashrc
sed -i 's/#alias /alias /g' ~/.bashrc

#-------------------------- END: Preparing bash ---------------------------

#--------------------- Installing Drop ------------------------------------
echo "Installing Drop ..."
sudo git clone https://github.com/backdrop-contrib/drop.git /usr/src/drop
sudo ln -s /usr/src/drop/drop /usr/local/bin/drop
#--------------------- END: Installing Drop -------------------------------

#--------------------- Installing Backdrop Console ------------------------
echo "Installing Backdrop Console ..."
sudo git clone https://github.com/backdrop-contrib/b.git /usr/src/b
echo "alias b='php /usr/src/b/b.php'" >> ~/.bashrc
source ~/.bashrc
#--------------------- END: Installing Backdrop Console -------------------

#------------------------------- Execution --------------------------------

# Project initialization steps
fix_permissions
time site_install

#-------------------------- END: Execution --------------------------------

#-------------------------- Development modules ---------------------------

cd $DOCROOT_PATH
drop -y dl devel && drop -y en devel
drop -y dl demo && drop -y en demo
drop -y dl search_krumo && drop -y en search_krumo
drop -y dl coder_upgrade && drop -y en coder_upgrade
drop -y dl coder_review && drop -y en coder_review

#-------------------------- END: Development modules ----------------------

