#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
FILESDIR_PATH="${DOCROOT_PATH}/files/"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${FILESDIR_PATH}"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH
	
	#--------------------- Installing Brush ------------------------------------
	echo "Installing Brush ..."
	sudo git clone https://github.com/backdrop-contrib/brush.git /var/www/brush
	sudo ln -s /var/www/brush/brush /usr/local/bin/brush
	#--------------------- END: Installing Brush -------------------------------
	 
	echo "Downloading Backdrop Drush Commands..."
	sudo rm -rf ~/.drush/backdrop
	sudo git clone https://github.com/backdrop-contrib/drush.git ~/.drush/backdrop

	# drush si standard \
	# -y \
	# --site-name='AltaGrade Developer Stack' \
	# --db-url='mysqli://user:user@db/default' \
	# --account-mail="admin@example.com" \
	# --account-name="admin" \
	# --account-pass="admin" || true
	
	# Alternative way to switch to until 
	# https://github.com/backdrop-contrib/drush/issues/195 is resolved.
	cd $DOCROOT_PATH
	./core/scripts/install.sh \
  	--db-url='mysql://user:user@db/default' \
	--account-mail="admin@example.com" \
	--account-name="admin" \
	--account-pass="admin" \
	--site-mail="admin@example.com" \
  	--site-name='AltaGrade Developer Stack'
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Preparing bash --------------------------------

sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/g' ~/.bashrc
sed -i 's/#alias /alias /g' ~/.bashrc

#-------------------------- END: Preparing bash ---------------------------

#--------------------- Installing Backdrop Console ------------------------
echo "Installing Backdrop Console ..."
sudo git clone https://github.com/backdrop-contrib/b.git /usr/src/b
echo "alias b='php /usr/src/b/b.php'" >> ~/.bashrc
source ~/.bashrc
#--------------------- END: Installing Backdrop Console -------------------

#------------------------------- Execution --------------------------------

# Project initialization steps
fix_permissions
time site_install

#-------------------------- END: Execution --------------------------------

#-------------------------- Development modules ---------------------------

cd $DOCROOT_PATH
brush -y en shortcut
brush -y en devel
brush -y en search_krumo
brush -y en coder_upgrade
brush -y en coder_review
brush -y en default_views_config
#-------------------------- END: Development modules ----------------------

#-------------------------- Additional modules ---------------------------
brush -y dl autologout
brush -y dl honeypot
brush -y dl passphrase_policy
brush -y dl remove_generator
brush -y dl session_limit
#-------------------------- END: Additional modules ----------------------

#----------------------- Additional Packages -------------------------
# sudo apt-get update 
# sudo apt-get install mlocate locate
# sudo updatedb

